- name: Allow access from patroni-node1 to node 1
  hosts: node1-postgresql
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        append_pg_hba_allow_network: "{{ hostvars['patroni-node1']['internal_host'] }}"
        append_pg_hba_entry: "host replication all {{ hostvars['patroni-node1']['internal_host'] }}/32 trust"
  roles:
    - append_pg_hba

- name: "PostgreSQL installation"
  hosts: patroni-node1
  become: true
  roles:
    - postgresql_install

- name: "PostgreSQL installation"
  hosts: patroni-node2
  become: true
  roles:
    - postgresql_install

- name: "PostgreSQL installation"
  hosts: patroni-node3
  become: true
  roles:
    - postgresql_install

- name: Install etcd on etcd1
  hosts: etcd1
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_advertize_ip: "{{ hostvars['etcd1']['internal_host'] }}"
  roles:
    - etcd

- name: "Stop directus container"
  hosts: directus
  tasks:
    - name: "Create Directus container"
      community.docker.docker_container:
        name: directus
        state: stopped

- name: Install patroni
  hosts: patroni-node1
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_ip: "{{ hostvars['etcd1']['internal_host'] }}"
        host_ip: "{{ hostvars['patroni-node1']['internal_host'] }}"
        directus_primary_node: "{{ hostvars['node1-postgresql']['internal_host'] }}"
        hba_units:
          - local all all peer
          - host all all 127.0.0.1/32 trust
          - local replication all peer
          - host replication replication {{ hostvars['patroni-node2']['internal_host'] }}/32 trust
          - host replication replication {{ hostvars['patroni-node3']['internal_host'] }}/32 trust
          - host all all 0.0.0.0/0 md5
          - host all postgres_exporter 10.100.0.0/24 md5
  roles:
    - patroni_primary

- name: Wait for patroni-node1 to become leader
  hosts: patroni-node1
  tasks:
    - name: Wait until Patroni leader is available
      ansible.builtin.uri:
        url: "http://127.0.0.1:8008"
        return_content: true
      register: result
      until: result.json.role == "primary"
      retries: 12
      delay: 3

- name: Install patroni
  hosts: patroni-node2
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_ip: "{{ hostvars['etcd1']['internal_host'] }}"
        host_ip: "{{ hostvars['patroni-node2']['internal_host'] }}"
        hba_units:
          - local all all peer
          - host all all 127.0.0.1/32 trust
          - local replication all peer
          - host replication replication {{ hostvars['patroni-node1']['internal_host'] }}/32 trust
          - host replication replication {{ hostvars['patroni-node3']['internal_host'] }}/32 trust
          - host all all 0.0.0.0/0 md5
          - host all postgres_exporter 10.100.0.0/24 md5
  roles:
    - patroni_replica

- name: Install patroni
  hosts: patroni-node3
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_ip: "{{ hostvars['etcd1']['internal_host'] }}"
        host_ip: "{{ hostvars['patroni-node3']['internal_host'] }}"
        hba_units:
          - local all all peer
          - host all all 127.0.0.1/32 trust
          - local replication all peer
          - host replication replication {{ hostvars['patroni-node1']['internal_host'] }}/32 trust
          - host replication replication {{ hostvars['patroni-node2']['internal_host'] }}/32 trust
          - host all all 0.0.0.0/0 md5
          - host all postgres_exporter 10.100.0.0/24 md5
  roles:
    - patroni_replica

- name: Install HAProxy for Patroni
  hosts: haproxy1
  become: true
  pre_tasks:
    - name: Set Patroni cluster nodes as facts
      ansible.builtin.set_fact:
        patroni_nodes:
          - name: patroni-node1
            ip: "{{ hostvars['patroni-node1']['internal_host'] }}"
          - name: patroni-node2
            ip: "{{ hostvars['patroni-node2']['internal_host'] }}"
          - name: patroni-node3
            ip: "{{ hostvars['patroni-node3']['internal_host'] }}"
        haproxy_port: 5432
        restapi_port: 8008
  roles:
    - haproxy

- name: "Docker installation"
  hosts: [patroni-node1, patroni-node2, patroni-node3]
  become: true
  serial: 1  # Запускать задачи по очереди на каждом хосте
  roles:
    - docker_install

- name: "Create patroni-node1 postgres_exporter container"
  hosts: patroni-node1
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        monitoring_net_subnet: "10.100.0.0/24"
        postgres_exporter_ip: "10.100.0.100"
        postgres_host: "{{ hostvars['patroni-node1']['internal_host'] }}"
        postgres_port: "5432"
        postgres_db: "postgres"
        postgres_user: "postgres_exporter"
        postgres_password: "postgres_exporter"
  roles:
    - create_postgres_exporter_container

- name: "Create patroni-node2 postgres_exporter container"
  hosts: patroni-node2
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        monitoring_net_subnet: "10.100.0.0/24"
        postgres_exporter_ip: "10.100.0.100"
        postgres_host: "{{ hostvars['patroni-node2']['internal_host'] }}"
        postgres_port: "5432"
        postgres_db: "postgres"
        postgres_user: "postgres_exporter"
        postgres_password: "postgres_exporter"
  roles:
    - create_postgres_exporter_container

- name: "Create patroni-node1 postgres_exporter container"
  hosts: patroni-node3
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        monitoring_net_subnet: "10.100.0.0/24"
        postgres_exporter_ip: "10.100.0.100"
        postgres_host: "{{ hostvars['patroni-node3']['internal_host'] }}"
        postgres_port: "5432"
        postgres_db: "postgres"
        postgres_user: "postgres_exporter"
        postgres_password: "postgres_exporter"
  roles:
    - create_postgres_exporter_container

- name: "Create Directus container to haproxy"
  hosts: directus
  tasks:
    - name: Create Directus container
      community.docker.docker_container:
        name: directus
        image: directus/directus:latest
        state: started
        restart_policy: always
        ports:
          - "8055:8055"
        volumes:
          - /opt/directus/uploads:/directus/uploads
          - /opt/directus/extensions:/directus/extensions
        env:
          SECRET: "replace-with-secure-random-value"
          DB_CLIENT: "pg"
          DB_HOST: "{{ hostvars['haproxy1']['internal_host'] }}"
          DB_PORT: "5432"
          DB_DATABASE: "directus"
          DB_USER: "directus"
          DB_PASSWORD: "directus"
          CACHE_ENABLED: "false"
          ADMIN_EMAIL: "admin@example.com"
          ADMIN_PASSWORD: "d1r3ctu5"
        exposed_ports:
          - "8055"
