- name: "Docker installation"
  hosts: [node1-postgresql, node2-postgresql, node3-monitoring]
  become: true
  serial: 1  # Запускать задачи по очереди на каждом хосте
  roles:
    - docker_install

- name: Allow access from exporter to node 1
  hosts: node1-postgresql
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        append_pg_hba_allow_network: "10.100.0.0/24"
        append_pg_hba_entry: "host all postgres_exporter 10.100.0.0/24 md5"
  roles:
    - append_pg_hba

- name: Allow access from exporter to node 2
  hosts: node2-postgresql
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        append_pg_hba_allow_network: "10.100.0.0/24"
        append_pg_hba_entry: "host all postgres_exporter 10.100.0.0/24 md5"
  roles:
    - append_pg_hba

- name: "Create postgres_exporter user"
  hosts: node1-postgresql # Создаем только на primary узле
  become: true
  roles:
    - create_postgres_exporter

- name: "Create node1 postgres_exporter container"
  hosts: node1-postgresql
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        monitoring_net_subnet: "10.100.0.0/24"
        postgres_exporter_ip: "10.100.0.100"
        postgres_host: "{{ hostvars['node1-postgresql']['internal_host'] }}"
        postgres_port: "5432"
        postgres_db: "postgres"
        postgres_user: "postgres_exporter"
        postgres_password: "postgres_exporter"
  roles:
    - create_postgres_exporter_container

- name: "Create node2 postgres_exporter container"
  hosts: node2-postgresql
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        monitoring_net_subnet: "10.100.0.0/24"
        postgres_exporter_ip: "10.100.0.100"
        postgres_host: "{{ hostvars['node2-postgresql']['internal_host'] }}"
        postgres_port: "5432"
        postgres_db: "postgres"
        postgres_user: "postgres_exporter"
        postgres_password: "postgres_exporter"
  roles:
    - create_postgres_exporter_container

- name: "Create prometheus container"
  hosts: node3-monitoring
  become: true
  pre_tasks:
    - name: Set prometheus_targets dynamically from hostvars
      ansible.builtin.set_fact:
        prometheus_targets:
          - { ip: "{{ hostvars['node1-postgresql']['internal_host'] }}", port: "9187" }
          - { ip: "{{ hostvars['node2-postgresql']['internal_host'] }}", port: "9187" }
          - { ip: "{{ hostvars['patroni-node1']['internal_host'] }}", port: "9187" }
          - { ip: "{{ hostvars['patroni-node2']['internal_host'] }}", port: "9187" }
          - { ip: "{{ hostvars['patroni-node3']['internal_host'] }}", port: "9187" }
  roles:
    - setup_prometheus

- name: "Create grafana container"
  hosts: node3-monitoring
  become: true
  roles:
    - setup_grafana
