- name: Allow access from patroni-node1 to node 1
  hosts: node1-postgresql
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        append_pg_hba_allow_network: "192.168.56.80/32"
        append_pg_hba_entry: "host replication all 192.168.56.80/32 trust"
  roles:
    - append_pg_hba

- name: "PostgreSQL installation"
  hosts: patroni-node1
  become: true
  roles:
    - postgresql_install

- name: "PostgreSQL installation"
  hosts: patroni-node2
  become: true
  roles:
    - postgresql_install

- name: "PostgreSQL installation"
  hosts: patroni-node3
  become: true
  roles:
    - postgresql_install

- name: Install etcd on etcd1
  hosts: etcd1
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_advertize_ip: "{{ hostvars['etcd1']['internal_host'] }}"
  roles:
    - etcd

- name: Install patroni
  hosts: patroni-node1
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_ip: "{{ hostvars['etcd1']['internal_host'] }}"
        host_ip: "{{ hostvars['patroni-node1']['internal_host'] }}"
        hba_units:
          - local all all peer
          - host all all 127.0.0.1/32 trust
          - local replication all peer
          - host replication replication 192.168.56.81/32 trust
          - host replication replication 192.168.56.82/32 trust
          - host all all 0.0.0.0/0 md5
          - host all postgres_exporter 10.100.0.0/24 md5
  roles:
    - patroni_primary

- name: Wait for patroni-node1 to become leader
  hosts: patroni-node1
  tasks:
    - name: Wait until Patroni leader is available
      ansible.builtin.uri:
        url: "http://127.0.0.1:8008"
        return_content: true
      register: result
      until: result.json.role == "primary"
      retries: 12
      delay: 3

- name: Install patroni
  hosts: patroni-node2
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_ip: "{{ hostvars['etcd1']['internal_host'] }}"
        host_ip: "{{ hostvars['patroni-node2']['internal_host'] }}"
        hba_units:
          - host replication replication 192.168.56.80/32 trust
          - host replication replication 192.168.56.82/32 trust
          - host replication replication 192.168.56.81/32 trust
          - host all all 0.0.0.0/0 md5
          - host all postgres_exporter 10.100.0.0/24 md5
  roles:
    - patroni_replica

- name: Install patroni
  hosts: patroni-node3
  become: true
  pre_tasks:
    - name: Set node facts
      ansible.builtin.set_fact:
        etcd_ip: "{{ hostvars['etcd1']['internal_host'] }}"
        host_ip: "{{ hostvars['patroni-node3']['internal_host'] }}"
        hba_units:
          - host replication replication 192.168.56.80/32 trust
          - host replication replication 192.168.56.82/32 trust
          - host replication replication 192.168.56.81/32 trust
          - host all all 0.0.0.0/0 md5
          - host all postgres_exporter 10.100.0.0/24 md5
  roles:
    - patroni_replica

- name: Install HAProxy for Patroni
  hosts: haproxy1
  become: true
  pre_tasks:
    - name: Set Patroni cluster nodes as facts
      ansible.builtin.set_fact:
        patroni_nodes:
          - name: patroni-node1
            ip: "{{ hostvars['patroni-node1']['internal_host'] }}"
          - name: patroni-node2
            ip: "{{ hostvars['patroni-node2']['internal_host'] }}"
          - name: patroni-node3
            ip: "{{ hostvars['patroni-node3']['internal_host'] }}"
        haproxy_port: 5432
        restapi_port: 8008
  roles:
    - haproxy
